### ISSUE TITLE
[Feature]: 

### ISSUE THREAD

**Issue by Morriaty-The-Murderer** [modelscope/agentscope#252]
**Is your feature request related to a problem? Please describe.**
I'm trying to implement a `GroupChatPipeline` that agents can freely talk rather than speak one by one sequencely
```yaml
SisterAgent: @MomAgent mommmmm! Tom hit me!!!!
MomAgent: oh my baby, let me check your injuries
MomAgent: em fine. That's not a big problem
SisterAgent: ouch! mom I really feel hurt
MomAgent: TOM YOU BASTARD! COME HERE RIGHT NOW!
BrotherAgent: what happended?
```

**Describe the solution you'd like**
```python3
# -*- coding:utf-8 -*-
# built-in packages
from typing import Callable, List

# third-party packages
from agentscope.agents import AgentBase


# self-defined packages


class GroupContext(object):
    pass


class BaseAgentAttendStrategy(object):
    # should an agent attend the group chat of current topic?
    pass


class KeywordsAgentAttendStrategy(BaseAgentAttendStrategy):
    # attend current topic if match some keywords
    pass


class BeenMentionedAgentAttendStrategy(BaseAgentAttendStrategy):
    # attend current topic if been mentioned
    pass


class AgentWithAttendStrategy(object):
    agent: AgentBase
    attend_strategies: List[BaseAgentAttendStrategy]


class GroupChatPipeline(object):
    def __init__(self):
        self.context = GroupContext()
        self.members: List[AgentWithAttendStrategy] = []

    def trigger_next_speaker(self, msg) -> AgentBase:
        pass

    def __call__(self,
                 start_agent: AgentBase,
                 start_words: str,
                 max_rounds: int,
                 ending_func: Callable[[GroupContext], bool]
                 ):
        next_speaker = start_agent
        msg = start_words
        n_round = 0
        while n_round < max_rounds and not ending_func(self.context):
            n_round += 1
            msg = next_speaker(msg)
            next_speaker = self.trigger_next_speaker(msg)
```

**Additional context**
I am wondering:
1. Is there any existing workaround functions or tools to achieve the `GroupChatPipeline`?
2. if Q1 answer is not. Do the team have a plan to make something alike?
